/**
 * Centralized error codes ENUM for all API routes.
 * Every error response SHOULD include a `code` field for client-side handling.
 */

export const ErrorCodes = {
  // ── Authentication (AUTH_xxx) ──
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_INVALID_SESSION: 'AUTH_INVALID_SESSION',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_NOT_CONFIRMED: 'AUTH_EMAIL_NOT_CONFIRMED',
  AUTH_PASSWORD_CHANGE_FAILED: 'AUTH_PASSWORD_CHANGE_FAILED',
  AUTH_PASSWORD_VERIFY_FAILED: 'AUTH_PASSWORD_VERIFY_FAILED',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',

  // ── Authorization (FORBIDDEN_xxx) ──
  FORBIDDEN_INSUFFICIENT_ROLE: 'FORBIDDEN_INSUFFICIENT_ROLE',
  FORBIDDEN_NOT_OWNER: 'FORBIDDEN_NOT_OWNER',
  FORBIDDEN_BANNED: 'FORBIDDEN_BANNED',
  FORBIDDEN_STORE_SUSPENDED: 'FORBIDDEN_STORE_SUSPENDED',

  // ── Validation (VALID_xxx) ──
  VALID_MISSING_PARAMS: 'VALID_MISSING_PARAMS',
  VALID_INVALID_FORMAT: 'VALID_INVALID_FORMAT',
  VALID_INVALID_UUID: 'VALID_INVALID_UUID',
  VALID_MISSING_BODY: 'VALID_MISSING_BODY',
  VALID_FILE_TOO_LARGE: 'VALID_FILE_TOO_LARGE',
  VALID_INVALID_FILE_TYPE: 'VALID_INVALID_FILE_TYPE',

  // ── Resources (NOT_FOUND_xxx) ──
  NOT_FOUND_USER: 'NOT_FOUND_USER',
  NOT_FOUND_PRODUCT: 'NOT_FOUND_PRODUCT',
  NOT_FOUND_STORE: 'NOT_FOUND_STORE',
  NOT_FOUND_OFFER: 'NOT_FOUND_OFFER',
  NOT_FOUND_ORDER: 'NOT_FOUND_ORDER',
  NOT_FOUND_COMMENT: 'NOT_FOUND_COMMENT',
  NOT_FOUND_FOLLOW: 'NOT_FOUND_FOLLOW',
  NOT_FOUND_MESSAGE: 'NOT_FOUND_MESSAGE',
  NOT_FOUND_CATEGORY: 'NOT_FOUND_CATEGORY',

  // ── Conflicts (CONFLICT_xxx) ──
  CONFLICT_DUPLICATE: 'CONFLICT_DUPLICATE',
  CONFLICT_ALREADY_EXISTS: 'CONFLICT_ALREADY_EXISTS',
  CONFLICT_ALREADY_FOLLOWING: 'CONFLICT_ALREADY_FOLLOWING',

  // ── Rate Limiting (RATE_xxx) ──
  RATE_LIMITED: 'RATE_LIMITED',
  RATE_LIMITED_AUTH: 'RATE_LIMITED_AUTH',
  RATE_LIMITED_MUTATION: 'RATE_LIMITED_MUTATION',
  RATE_LIMITED_SEARCH: 'RATE_LIMITED_SEARCH',

  // ── External Services (EXT_xxx) ──

  // ── Internal Server (INTERNAL_xxx) ──
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INTERNAL_TIMEOUT: 'INTERNAL_TIMEOUT',
  INTERNAL_DB_ERROR: 'INTERNAL_DB_ERROR',
  INTERNAL_UNKNOWN: 'INTERNAL_UNKNOWN',

  // ── Business Logic (BIZ_xxx) ──
  BIZ_INSUFFICIENT_POINTS: 'BIZ_INSUFFICIENT_POINTS',
  BIZ_ORDER_CANNOT_CANCEL: 'BIZ_ORDER_CANNOT_CANCEL',
  BIZ_STORE_LIMIT_REACHED: 'BIZ_STORE_LIMIT_REACHED',
  BIZ_PRODUCT_LIMIT_REACHED: 'BIZ_PRODUCT_LIMIT_REACHED',
  BIZ_OFFER_EXPIRED: 'BIZ_OFFER_EXPIRED',
  BIZ_VERIFICATION_PENDING: 'BIZ_VERIFICATION_PENDING',
  BIZ_NOT_VERIFIED: 'BIZ_NOT_VERIFIED',
  BIZ_INVALID_COLOR: 'BIZ_INVALID_COLOR',
  BIZ_COOLDOWN: 'BIZ_COOLDOWN',

  // ── Chat (CHAT_xxx) ──
  CHAT_MISSING_PARAMS: 'CHAT_MISSING_PARAMS',
  CHAT_EMPTY_CONTENT: 'CHAT_EMPTY_CONTENT',
  CHAT_RECEIVER_NOT_FOUND: 'CHAT_RECEIVER_NOT_FOUND',
  CHAT_SEND_FAILED: 'CHAT_SEND_FAILED',
  CHAT_STORE_NOT_VERIFIED: 'CHAT_STORE_NOT_VERIFIED',

  // ── Diagnostics (DIAG_xxx) ──
  DIAG_DIAGNOSTICS_FAILED: 'DIAG_DIAGNOSTICS_FAILED',

  // ── System (SYS_xxx) ──
  SYS_SERVICE_UNAVAILABLE: 'SYS_SERVICE_UNAVAILABLE',
  SYS_MAINTENANCE: 'SYS_MAINTENANCE',
  SYS_PAYLOAD_TOO_LARGE: 'SYS_PAYLOAD_TOO_LARGE',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

/**
 * Classify an HTTP status code into an error code.
 * Used as fallback when no explicit code is provided.
 */
export function statusCodeToCode(status: number): ErrorCode {
  switch (status) {
    case 400: return ErrorCodes.VALID_MISSING_PARAMS;
    case 401: return ErrorCodes.AUTH_REQUIRED;
    case 403: return ErrorCodes.FORBIDDEN_INSUFFICIENT_ROLE;
    case 404: return ErrorCodes.NOT_FOUND_PRODUCT; // generic
    case 409: return ErrorCodes.CONFLICT_DUPLICATE;
    case 429: return ErrorCodes.RATE_LIMITED;
    case 503: return ErrorCodes.SYS_SERVICE_UNAVAILABLE;
    default:  return ErrorCodes.INTERNAL_ERROR;
  }
}
